name: Generate Semantic Release
on:
  push:
    branches: [ main, master ]
      
permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup dependencies
        run: |
          npm install @semantic-release/git @semantic-release/exec --no-save
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.DHWANI_FRAPPE_TOKEN  }}
          GITHUB_TOKEN: ${{ secrets.DHWANI_FRAPPE_TOKEN  }}
          GIT_AUTHOR_NAME: "Dhwani Release Bot"
          GIT_AUTHOR_EMAIL: "frappeteam@dhwaniris.com"
          GIT_COMMITTER_NAME: "Dhwani Release Bot"
          GIT_COMMITTER_EMAIL: "frappeteam@dhwaniris.com"
        run: npx semantic-release
